# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin (Git)
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include plugins for Ruby environment, bundler, Rails and Passenger
require "capistrano/rbenv"
require "capistrano/bundler"
require "capistrano/rails"
require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` directory
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
